# Generated by Django 3.0.8 on 2021-05-30 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_media_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='blogCreated',
            field=models.DateField(blank=True, null=True),
        ),
    ]
