# Generated by Django 3.0.8 on 2021-05-30 10:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('social_media_app', '0003_auto_20210530_1542'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='blogCategory',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='social_media_app.blog_Categorie'),
        ),
    ]
