# Generated by Django 3.0.8 on 2021-05-30 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_media_app', '0005_auto_20210530_1557'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='blogImg',
            new_name='blogImgOne',
        ),
        migrations.AddField(
            model_name='blog',
            name='blogContentTwo',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='blogImgThree',
            field=models.ImageField(blank=True, default='', null=True, upload_to='Blogimages/'),
        ),
        migrations.AddField(
            model_name='blog',
            name='blogImgTwo',
            field=models.ImageField(default='', upload_to='Blogimages/'),
        ),
    ]
