# Generated by Django 3.0.8 on 2021-05-30 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social_media_app', '0006_auto_20210530_1655'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='blogImgThree',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='blogImgTwo',
        ),
    ]
