# Generated by Django 3.0.8 on 2021-05-31 07:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social_media_app', '0007_auto_20210530_2204'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='blogContentTwo',
        ),
    ]
