# Generated by Django 3.0.8 on 2021-05-31 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_media_app', '0008_remove_blog_blogcontenttwo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='blogCreated',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='blog',
            name='blogImgOne',
            field=models.ImageField(blank=True, default='', null=True, upload_to='Blogimages/'),
        ),
    ]
