# Generated by Django 3.0.8 on 2021-05-31 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_media_app', '0010_auto_20210531_1641'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='blogImgOne',
            field=models.ImageField(default='', upload_to='Blogimages/'),
        ),
    ]
