# Generated by Django 3.1.7 on 2021-06-06 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_media_app', '0011_auto_20210531_1722'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='cover',
            field=models.ImageField(blank=True, default='cover.png', null=True, upload_to='cover_pics/'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='pfp',
            field=models.ImageField(blank=True, default='profile.png', null=True, upload_to='profile_pics/'),
        ),
    ]
